# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cislo_faktury', models.CharField(max_length=150)),
                ('datum_vystavenia', models.DateField()),
                ('datum_splatnosti', models.DateField()),
                ('datum_dodania', models.DateField()),
                ('konstantny_symbol', models.CharField(max_length=150)),
                ('doprava', models.CharField(blank=True, max_length=150)),
                ('komentar', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazov', models.CharField(max_length=200)),
                ('meno', models.CharField(max_length=50)),
                ('priezvisko', models.CharField(max_length=50)),
                ('ico', models.CharField(max_length=50)),
                ('dic', models.CharField(max_length=50)),
                ('banka', models.CharField(max_length=100)),
                ('cislo_uctu', models.CharField(max_length=100)),
                ('cislo_swift', models.CharField(choices=[('----', 'none'), ('SUBASKBX', 'Všeobecná úverová banka, a. s.'), ('GIBASKBX', 'Slovenská sporiteľňa, a. s.'), ('TATRSKBX', 'Tatra banka, a. s.'), ('BREXSKBX', 'MBANK – BRE Bank SA, pobočka zahraničnej banky mBank v SR'), ('UNCRSKBX', 'UniCredit Bank Czech Republic and Slovakia, a. s., pobočka zahr. banky'), ('CEKOSKBX', 'ČSOB – Československá obchodná banka, a.s.')], max_length=8)),
                ('platca_DPH', models.CharField(choices=[('platiDPH', 'ano'), ('neplatcaDPH', 'nie')], max_length=11)),
                ('telefon', models.CharField(max_length=50)),
                ('adresa_ulica', models.CharField(max_length=200)),
                ('adresa_mesto', models.CharField(max_length=90)),
                ('adresa_PSC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Polozky',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazov', models.CharField(max_length=300)),
                ('mnozstvo', models.CharField(max_length=100)),
                ('kod', models.CharField(blank=True, max_length=100)),
                ('cena', models.CharField(max_length=100)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Faktura')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazov', models.CharField(blank=True, max_length=200)),
                ('meno', models.CharField(blank=True, max_length=50)),
                ('cislo', models.CharField(blank=True, max_length=50)),
                ('priezvisko', models.CharField(blank=True, max_length=50)),
                ('adresa_ulica', models.CharField(max_length=200)),
                ('adresa_mesto', models.CharField(max_length=90)),
                ('adresa_psc', models.CharField(max_length=20)),
                ('ico', models.CharField(max_length=50)),
                ('dic', models.CharField(max_length=50)),
                ('icdph', models.CharField(max_length=50)),
                ('banka', models.CharField(max_length=100)),
                ('cislo_uctu', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Firma')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Login')),
            ],
        ),
        migrations.AddField(
            model_name='firma',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Login'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='created_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Zakaznik'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Firma'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Login'),
        ),
    ]
