# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20170519_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='cislo_swift',
            field=models.CharField(choices=[('', 'vyberte'), ('SUBASKBX', 'Všeobecná úverová banka, a. s.'), ('GIBASKBX', 'Slovenská sporiteľňa, a. s.'), ('TATRSKBX', 'Tatra banka, a. s.'), ('BREXSKBX', 'MBANK – BRE Bank SA, pobočka zahraničnej banky mBank v SR'), ('UNCRSKBX', 'UniCredit Bank Czech Republic and Slovakia, a. s., pobočka zahr. banky'), ('CEKOSKBX', 'ČSOB – Československá obchodná banka, a.s.')], default='', max_length=8),
        ),
    ]
