# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20170519_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='platca_DPH',
            field=models.CharField(choices=[('20', 'ano'), ('0', 'nie')], max_length=2),
        ),
        migrations.AlterField(
            model_name='polozky',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='polozky',
            name='mnozstvo',
            field=models.IntegerField(),
        ),
    ]
