# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20170522_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='polozky',
            name='spolu',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name=invoice.models.Polozky.spocitaj),
            preserve_default=False,
        ),
    ]
