# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_polozky_spolu'),
    ]

    operations = [
        migrations.AddField(
            model_name='polozky',
            name='dan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
