# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_polozky_dan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polozky',
            name='spolu',
        ),
        migrations.AddField(
            model_name='polozky',
            name='spocitaj',
            field=models.CharField(default='0', editable=False, max_length=2),
        ),
    ]
