# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20170522_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polozky',
            name='spocitaj',
            field=models.IntegerField(editable=False, verbose_name=invoice.models.Polozky.spolu),
        ),
    ]
