# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20170523_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='uhradena',
            field=models.CharField(choices=[('1', 'ano'), ('0', 'nie')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='cislo_faktury',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='polozky',
            name='mnozstvo',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='polozky',
            name='spocitaj',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
